FROM debezium/connect:2.2

USER root

# Drop in the FileStreamSourceConnector plugin
RUN mkdir -p /kafka/connect \
 && curl -sL \
    https://repo1.maven.org/maven2/org/apache/kafka/connect/kafka-connect-file/3.5.1/kafka-connect-file-3.5.1.jar \
    -o /kafka/connect/kafka-connect-file-3.5.1.jar

USER 1001
