import time
import json
import os
import traceback
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler
from app.utils.jira_notifier import create_jira_ticket

MCP_STORE = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "mcp_store"))

class JiraMCPHandler(FileSystemEventHandler):
    def on_created(self, event):
        if event.is_directory or not event.src_path.endswith(".json"):
            return

        # Retry reading the file up to 5 times
        for _ in range(5):
            try:
                with open(event.src_path, "r") as f:
                    mcp_data = json.load(f)
                break
            except (json.JSONDecodeError, IOError):
                time.sleep(0.5)
        else:
            print(f"❌ Could not read JSON file: {event.src_path}")
            return

        if mcp_data.get("type") == "rca_report":
            payload = mcp_data.get("payload", {})
            print("📦 Payload received from MCP:")
            print(json.dumps(payload, indent=2))

            incident_id = payload.get("incident_id")
            service = payload.get("service", "Unknown")
            timestamp = payload.get("timestamp", "Unknown")
            root_cause = payload.get("root_cause", "N/A")
            recommendation = payload.get("recommendation", "N/A")

            if not incident_id:
                print(f"⚠️ No incident_id in MCP file: {event.src_path}")
                return

            summary = f"[Incident {incident_id}] RCA: {root_cause[:80]}"

            description = f"""\
📄 *Root Cause Analysis Report*

*🔎 Incident ID:* `{incident_id}`
*📍 Service:* `{service}`
*🕒 Timestamp:* `{timestamp}`

---

🧠 *Root Cause:*
{root_cause}

✅ *Recommendation:*
{recommendation}

---

📁 *Metadata*
- Source: `rca_agent`
- Created via MCP: ✅
- Auto-generated by PowerOps RCA Sync Tool
"""

            print(f"📄 Summary: {summary}")
            print(f"📝 Description: {description}")

            try:
                key = create_jira_ticket(summary, description)
                print(f"✅ Created Jira ticket {key} for file: {event.src_path}")
            except Exception as e:
                print(f"❌ Jira creation failed: {e}")
                traceback.print_exc()

def run_jira_sync():
    observer = Observer()
    handler = JiraMCPHandler()
    observer.schedule(handler, MCP_STORE, recursive=False)
    observer.start()
    print("📡 Jira MCP Tool is running...")

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        observer.stop()
    observer.join()

if __name__ == "__main__":
    run_jira_sync()
