import time
import json
import os
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler
from app.utils.slack_notifier import send_to_slack

MCP_STORE = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "mcp_store"))

class SlackMCPHandler(FileSystemEventHandler):
    def on_created(self, event):
        if event.is_directory or not event.src_path.endswith(".json"):
            return

        time.sleep(0.5)
        with open(event.src_path, "r") as f:
            mcp_data = json.load(f)

        if mcp_data.get("type") == "rca_report":
            payload = mcp_data.get("payload", {})
            incident_id = payload.get("incident_id")
            service = payload.get("service", "Unknown")
            timestamp = payload.get("timestamp", "Unknown")
            root_cause = payload.get("root_cause", "N/A")
            recommendation = payload.get("recommendation", "N/A")

            blocks = [
                {
                    "type": "header",
                    "text": {"type": "plain_text", "text": f"🛠️ RCA Report for Incident #{incident_id}"}
                },
                {
                    "type": "section",
                    "fields": [
                        {"type": "mrkdwn", "text": f"*📍 Service:*\n`{service}`"},
                        {"type": "mrkdwn", "text": f"*🕒 Timestamp:*\n`{timestamp}`"},
                    ]
                },
                {"type": "divider"},
                {
                    "type": "section",
                    "text": {"type": "mrkdwn", "text": f"*🧠 Root Cause:*\n{root_cause}"}
                },
                {
                    "type": "section",
                    "text": {"type": "mrkdwn", "text": f"*✅ Recommendation:*\n{recommendation}"}
                },
                {
                    "type": "context",
                    "elements": [
                        {"type": "mrkdwn", "text": "🔎 _Generated by PowerOps RCA Agent_"}
                    ]
                }
            ]

            send_to_slack(blocks, is_block=True)
            print(f"✅ Sent Slack block notification for file: {event.src_path}")

def run_slack_sync():
    observer = Observer()
    handler = SlackMCPHandler()
    observer.schedule(handler, MCP_STORE, recursive=False)
    observer.start()
    print("📡 Slack MCP Tool is running...")

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        observer.stop()
    observer.join()

if __name__ == "__main__":
    run_slack_sync()
