"""Initial full schema

Revision ID: 1cf389de6007
Revises: 
Create Date: 2025-07-08 21:50:14.371398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1cf389de6007'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoint_types',
    sa.Column('endpoint_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('endpoint_type_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('environments',
    sa.Column('environment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('environment_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('incident_statuses',
    sa.Column('status_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('status_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('incident_types',
    sa.Column('incident_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('incident_type_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('severity_levels',
    sa.Column('severity_level_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('impact_score', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sla_hours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('severity_level_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('slack_channel', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('locations',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('models',
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('model_id')
    )
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_models_model_id'), ['model_id'], unique=False)

    op.create_table('shap_explanations',
    sa.Column('explanation_id', sa.UUID(), nullable=False),
    sa.Column('explanation_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('explanation_id')
    )
    with op.batch_alter_table('shap_explanations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shap_explanations_explanation_id'), ['explanation_id'], unique=False)

    op.create_table('services',
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('criticality_level', sa.String(length=20), nullable=True),
    sa.Column('owner_team_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('telemetry_sources',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('endpoint_type_id', sa.UUID(), nullable=True),
    sa.Column('environment_id', sa.UUID(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('metadata_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_type_id'], ['endpoint_types.endpoint_type_id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.environment_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.PrimaryKeyConstraint('source_id')
    )
    
    op.create_table('incidents',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('incident_type_id', sa.UUID(), nullable=False),
    sa.Column('severity_level_id', sa.UUID(), nullable=False),
    sa.Column('status_id', sa.UUID(), nullable=False),
    sa.Column('root_cause_id', sa.UUID(), nullable=True),
    sa.Column('start_timestamp', sa.DateTime(), nullable=False),
    sa.Column('end_timestamp', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('escalation_level', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incident_type_id'], ['incident_types.incident_type_id'], ),
    sa.ForeignKeyConstraint(['root_cause_id'], ['rca_analysis.rca_id'], name='fk_incident_root_cause', use_alter=True, deferrable=True, initially='DEFERRED'),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], ),
    sa.ForeignKeyConstraint(['severity_level_id'], ['severity_levels.severity_level_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['telemetry_sources.source_id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['incident_statuses.status_id'], ),
    sa.PrimaryKeyConstraint('incident_id')
    )        
    op.create_table('rca_analysis',
    sa.Column('rca_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('analysis_method', sa.String(length=50), nullable=False),
    sa.Column('root_cause_node_id', sa.UUID(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('contributing_factors', sa.JSON(), nullable=True),
    sa.Column('recommendations', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('analysis_timestamp', sa.DateTime(), nullable=False),
    sa.Column('analyst_team_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analyst_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.PrimaryKeyConstraint('rca_id')
    )

    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('predictions',
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.Column('input_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prediction_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('prediction_timestamp', sa.DateTime(), nullable=True),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('explanation_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['explanation_id'], ['shap_explanations.explanation_id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    
    
    op.create_table('anomalies',
    sa.Column('anomaly_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('detection_method', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('anomaly_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['telemetry_sources.source_id'], ),
    sa.PrimaryKeyConstraint('anomaly_id')
    )
    op.create_table('dependency_graph',
    sa.Column('dependency_id', sa.UUID(), nullable=False),
    sa.Column('dependent_service_id', sa.UUID(), nullable=True),
    sa.Column('dependency_service_id', sa.UUID(), nullable=True),
    sa.Column('dependency_type', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dependency_service_id'], ['services.service_id'], ),
    sa.ForeignKeyConstraint(['dependent_service_id'], ['services.service_id'], ),
    sa.PrimaryKeyConstraint('dependency_id')
    )
    op.create_table('runbooks',
    sa.Column('runbook_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('incident_type_id', sa.UUID(), nullable=True),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incident_type_id'], ['incident_types.incident_type_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('runbook_id')
    )
    op.create_table('service_endpoints',
    sa.Column('service_endpoint_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('role_in_service', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['telemetry_sources.source_id'], ),
    sa.PrimaryKeyConstraint('service_endpoint_id')
    )
    op.create_table('team_endpoint_ownership',
    sa.Column('ownership_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['telemetry_sources.source_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('ownership_id'),
    sa.UniqueConstraint('team_id', 'source_id', name='uq_team_source')
    )
    op.create_table('runbook_steps',
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('runbook_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('command_or_script', sa.Text(), nullable=True),
    sa.Column('timeout_minutes', sa.Integer(), nullable=True),
    sa.Column('success_condition', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['runbook_id'], ['runbooks.runbook_id'], ),
    sa.PrimaryKeyConstraint('step_id')
    )
    op.create_table('response_actions',
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('runbook_id', sa.UUID(), nullable=True),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('executed_by_team_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('execution_log', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['executed_by_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.ForeignKeyConstraint(['runbook_id'], ['runbooks.runbook_id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['runbook_steps.step_id'], ),
    sa.PrimaryKeyConstraint('action_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response_actions')
    op.drop_table('runbook_steps')
    op.drop_table('team_endpoint_ownership')
    op.drop_table('service_endpoints')
    op.drop_table('runbooks')
    op.drop_table('dependency_graph')
    op.drop_table('anomalies')
    op.drop_table('telemetry_sources')
    op.drop_table('services')
    op.drop_table('predictions')
    op.drop_table('audit_logs')
    op.drop_table('teams')
    with op.batch_alter_table('shap_explanations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shap_explanations_explanation_id'))

    op.drop_table('shap_explanations')
    op.drop_table('severity_levels')
    op.drop_table('rca_analysis')
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_models_model_id'))

    op.drop_table('models')
    op.drop_table('locations')
    op.drop_table('incidents')
    op.drop_table('incident_types')
    op.drop_table('incident_statuses')
    op.drop_table('environments')
    op.drop_table('endpoint_types')
    # ### end Alembic commands ###
